
animal:
  name: 罐头基金

  # mysql 配置
  mysql:
    host: localhost
    port: 3306
    db: animal_fund
    username: root
    password: 123456
    druid:
      username: admin
      password: admin

  # redis 配置
  redis:
    host: localhost
    port: 6379
    db: 3
    password: password

  # 邮件配置
  mail:
    username: example@example.com
    password: password

  # oss 配置
  oss:
    access-key: access-key
    secret-key: secret-key
    endpoint: endpoint
    bucket-name: bucket-name
    host: host

  # 实名认证配置
  auth:
    url: http://dfidveri.market.alicloudapi.com/verify_id_name
    app-code: app-code


